"Create Input for a picture [ 11 WIP ⚠️]"
Ceaseless04/MapModel pull request #12
Opened 2022-10-28 19:02 UTC by catastrxphic

Created a function that accepts images from the local library, as well as a function that let the user preview the image once selected, if the image is changed the preview changes with it. When the user goes back on the form the last image preview stays.

**Type of change**

- [ ] Bug Fixes
- [ ] Breaking Change
- [x] New Feature

**Have you done the following?**

- [x] Pull from staging/master
- [x] document your changes above
- [x] assigned a code reviewer
- [x] Deleted the comments in this template

2022-11-01 17:41 UTC, leonkoech commented
Hello @catastrxphic , is this still WIP?

2022-11-02 07:06 UTC, catastrxphic commented
hey @leonkoech, no. I just put it literally as the name on the project Github, sorry. :)

2022-11-02 13:55 UTC, leonkoech commented
@catastrxphic haha that's okay. I changed the title to reflect the ticket number

2022-11-02 13:56 UTC, leonkoech commented on pages/auth.tsx
> +                error;
the error function should be an await error(code). We need to add the error code for this particular instance in the error file with a code. @catastrxphic

2022-11-02 13:58 UTC, leonkoech approved these changes
Approving for now, but we need to address the error component

2022-11-02 13:59 UTC, leonkoech commented
Also @catastrxphic Pul from staging and resolve any conflict before merging as it may break things considering staging was updated in the latest PR

2022-11-02 13:59 UTC, leonkoech requested changes
Pull from staging first

2022-11-02 14:01 UTC, leonkoech commented
Also you did an amazing job! congrats you're promoted to assistant technical director XD

2022-11-02 20:47 UTC, leonkoech approved these changes

2022-11-02 20:48 UTC, merged